### ISSUE TITLE
Investigate: equipAsChestArmor / configs not updating properly?

### ISSUE THREAD

**Issue by NorraV** [copygirl/WearableBackpacks#23] opened 2017-04-24 13:08 UTC
# If disabled, backpacks do not take up the player's chest armor equipment slot. Default: true.

if set to true it still added to chestslot ie unable to wear chest armor
so it does not change false nor true does not work while wearing a chestplate

**Comment by copygirl** [comment] 2017-04-24 14:37
Sorry. I'm not sure I understand. If you change the `equipAsChestArmor` option to `false`, the backpack should not use the chestplate armor slot when you equip it, and you can wear both. If set to `true` you can't equip both armor and backpacks.

This should work, unless you are playing on a multiplayer server, where only the **server**'s settings matter.

If something is unclear or I misunderstood, please explain.

**Comment by NorraV** [comment] 2017-04-24 16:11
well lets say it this way then
it makes no diffrence if I write true , or false in the config
does not work

**Comment by copygirl** [comment] 2017-04-24 17:33
The setting should be `false`.

> it makes no diffrence if I write true , or false in the config

Are you sure?
If so, which version of the mod are you using?

**Comment by NorraV** [comment] 2017-04-24 17:48
its on WearableBackpacks-1.11.2-2.3.0.jar

**Comment by copygirl** [comment] 2017-04-24 18:34
It works for me just fine.

![image](https://cloud.githubusercontent.com/assets/272586/25352628/fa1fc992-292c-11e7-8e8c-4c6079b82461.png)

![image](https://cloud.githubusercontent.com/assets/272586/25352620/f33bb7d0-292c-11e7-9760-8a140ee83720.png)

Are you playing Singleplayer or Multiplayer?

**Comment by NorraV** [comment] 2017-04-24 18:36
single have no forge server for that version yet

**Comment by NorraV** [comment] 2017-04-24 18:36
how do I get this ui ?

**Comment by copygirl** [comment] 2017-04-24 18:38
In the menu (main menu or ingame menu), click **Mods**, then select Wearable Backpacks in the list, then click **Config**.

**Comment by NorraV** [comment] 2017-04-24 19:11
https://www.dropbox.com/s/saskbwq8zagpspi/2017-04-24_21.08.47.png?dl=0

still does not work

**Comment by NorraV** [comment] 2017-04-24 19:14
got it finally , you HAVE to changed that while playing , doen't work wenn you are in titlescreen and change there

**Comment by NorraV** [comment] 2017-04-24 19:17
https://www.dropbox.com/s/m07k3ahl0wtovfl/2017-04-24_21.14.42.png?dl=0

**Comment by NorraV** [comment] 2017-04-24 19:22
:) thank you for the help

**Comment by NorraV** [comment] 2017-04-24 19:22
seems it does ingnore the config in that manner

**Comment by copygirl** [comment] 2017-04-24 20:39
Thank you. I'll see if I can figure out what's going wrong.

**Comment by NorraV** [comment] 2017-04-24 20:41
:) welcome, thank you too

**Comment by Endmateria** [comment] 2017-05-01 16:22
I'm having similar problems with the configs in 1.11.2
1.  I set a hotkey to be able to access my own backpack while equipped (after enabling the option in the configs ingame-singleplayer) and the hotkey would not work.
2. Tried to put diamond armor over the backpack while it was equipped in my inventory and the diamond armor disappeared.
3.  I have no armor equipped, the backpack is on the ground, and when I sneak crouch to pick it up I get a message saying "you already have a backpack equipped" (all four config options were set to true).
4.  The first time I joined the game, if I tried to break a backpack on the ground while standing... the backpack would disappear.  After a restart, I tried doing the same thing and the bag went into my storage.  So I basically did the same thing twice, and got two different results.

So... from my end, the mod seems glitchy at the moment.
MC 1.11.2
Forge 2286
Wearable Backpacks 2.3.0
(and I do have lots of other mods installed, don't know how relevant that is to the issue though)

I do like the concept of being able to see your backpack though, looks nice.  Would be nice if you could integrate it with Baubles (wearable accessories) and/or Cosmetic Armor Reworked.  Cosmetic Armor Reworked pretty much gives you cosmetic slots to put clothing/armor into (like Terraria).  It's got a cosmetic chest armor slot for example (which you can toggle visible or invisible).  In conclusion though, it might be easier to just scrap the backpack pickup system in favor of manually placing the backpack in the chest armor slot, as it would probably cause less issues.

**Comment by copygirl** [comment] 2017-05-01 17:55
Ah, I think the reason why I could not reproduce this issue is because I was using a newer unreleased version of the mod that overhauled the config system. Good news: It seems to be fixed. Bad news: I actually have to release it.

> Would be nice if you could integrate it with Baubles (wearable accessories) and/or Cosmetic Armor Reworked.

Baubles don't have an appropriate slot for the backpack and the backpack itself is anything but cosmetic, so no support for Cosmetic Armor Reworked.

> In conclusion though, it might be easier to just scrap the backpack pickup system in favor of manually placing the backpack in the chest armor slot, as it would probably cause less issues.

This causes all kinds of questions regarding the design. If you can equip it, can you unequip it just the same? What happens to the items in it? Do they drop on the ground? I won't have the item itself store the backpack contents. The mod is very deliberately designed this way and I love it!

**Comment by Endmateria** [comment] 2017-05-01 18:47
No I gotcha, you want the whole realism thingy, I was just making a suggestion in the name of practicality, and that suggestion was based on me having problems with the current version of the mod.  If you got it working right, then by all means keep it that way it is.  I would much rather use your mod than the "Backpacks!" mod given that 1. It's much more realistic (you can only carry one backpack at a time).  2.  The backpack's inventory box doesn't scroll off the screen (annoying).  3.  It's 1/13th the size of that mod (which is important when you're heavily modding).  If it works now, then I'll give it another shot haha.  In regards to the Cosmetic Armor mod though, I only mentioned it, because like Baubles, it has four slots that you can put decorative clothing in.... so you could wear armor and have a slot for a backpack (all it does is give you configuration/decorative slots to show or hide what you're wearing).  So the suggestion wasn't purely for cosmetic reasons, but for logistical ones i.e., it has a "backpack slot".  Regardless, most of what I said is redundant given that I was playing with a broken version of your mod.  Question though, will I still be able to see the backpack, even if I configure it to not use the armor slot?  I couldn't check before because I couldn't pick up the backpack.

**Comment by copygirl** [comment] 2017-05-01 21:17
> Question though, will I still be able to see the backpack, even if I configure it to not use the chest armor slot? I couldn't check before because I couldn't pick up the backpack.

Of course.

**Comment by copygirl** [comment] 2017-05-03 20:15
Should be fixed by b925a888fafc905ac89ae444287f827a169a035f for version 1.6.1 and 2.3.1.

**Comment by Endmateria** [comment] 2017-05-03 20:38
Thanks for letting me know, I'll test it but it'll take a little bit... had a hard drive crash two days ago and lost my entire .minecraft folder/mods/configs, not to mention everything else on C drive.  Sucks.  Oh well, I'll check it as soon as I get everything back in order... shouldn't take long.

**Comment by Endmateria** [comment] 2017-05-04 05:24
It's crashing against the newest build of Forge 2294.  https://gist.github.com/Endmateria/02ffbd3b662045c14d79493faf368521#file-crash-2017-05-04_01-19-19-client-txt

**Comment by copygirl** [comment] 2017-05-04 07:48
I apparently built it incorrectly. Compiling for two versions at once is frustrating sometimes.

**Comment by Endmateria** [comment] 2017-05-04 14:10
It's cool, take your time, I mean after all, building and compiling mods is something waaaay beyond my abilities, so respect for that hahaha.  I'll retest it for you whenever you're ready.

**Comment by Endmateria** [comment] 2017-05-05 00:38
K, I played with it a bit to try to find any bugs I could.  The only item from my list above that I was still able to reproduce, was #3.  I think it's the config option "equipAsChestArmor=true" that's causing the problem.  I initially set this to false, joined the game and was able to access the backpack in my inventory with a hotkey i.e., it worked perfectly.  So I left the game, set that option back to true, restarted the game (in the same world), and was not able to get the bag into my chest armor slot.  I tried restarting the game again and I tried spawning in a fresh backpack.  No luck.  In simple terms, it seems like when you set this config option to false, then it permanently stays false.

**Comment by Endmateria** [comment] 2017-05-05 00:49
Yeah, that's gotta be it cuz I just started a fresh world with that config set to true and it let me equip the bag into the armor slot.

**Comment by copygirl** [comment] 2017-05-05 09:02
@Endmateria If you can change the setting back and forth and have it work flawlessly without exiting the world or restarting, I will assume this is fixed.

**Comment by Endmateria** [comment] 2017-05-05 12:00
Once you set that config to false... it will never again let you wear the backpack as chest armor.  It doesn't matter if you set it back to true.  It doesn't matter if you leave the game or not.  So no, you can NOT "change the setting back and forth and have it work flawlessly without exiting the world or restarting".  If you set it to false and then back to true without leaving the game, then it will tell you that "you already have a backpack equipped" when you try to put it in your chest armor slot.

**Comment by copygirl** [comment] 2017-05-05 12:31
> If you set it to false and then back to true without leaving the game, then it will tell you that "you already have a backpack equipped" when you try to put it in your chest armor slot.

I can't reproduce this specifically. It may be very helpful if you could provide me with the steps I need to follow to run into this problem.

I have however found a different issue. When you change the setting and have a armor equipped, and unequip the backpack, it will clear your armor slot (and you'll lose the armor).

**Comment by Endmateria** [comment] 2017-05-05 12:44
Forge 2294. Wearable Backpacks 2.3.2. JEI 4.3.4.273.

Start a fresh a fresh world.
Use JEI to spawn in a wearable backpack.
Place that bag on the ground.
Sneak/attack to equip that bag to the chest armor slot.
Place that bag back on the ground.
Go to mod configs (in game), set equipAsChestArmor=false.
Pick the bag back up (it should go into your inventory slot this time, rather than chest armor slot).
Go to mod configs, equipAsChestArmor=true.
Place backpack on the ground again.
Sneak/attack to equip bag to chest armor slot... get message "you already have a backpack equipped".

**Comment by Endmateria** [comment] 2017-05-05 12:52
There are some variables here, relevance is questionable.
1.  My backpack armor strength was set at 20.  I:armor=20
2.  My backpack size was set at 17x6.  S:size=[17x6]
3.  Self interaction was set to true.  B:enableSelfInteraction=true
4.  How you pick up the bag may be relevant (stand or crouch), cuz once you change the equipAsChestArmor=true to false, you can pick up the bag either way.

**Comment by copygirl** [comment] 2017-07-11 05:23
Closing since not reproducible on my end (and the issue is sort of old).

**Closed by copygirl** 2017-07-11 05:23 UTC
