### ISSUE TITLE
Crash when getting to close to placed backback

### ISSUE THREAD

**Issue by yosoDev** [copygirl/WearableBackpacks#93] opened 2018-09-26 20:16 UTC
My friend put down a backpack and then suddenly crashed. She kept on crashing until I teleported her to a different location. I went to the location where the backback is placed and I also crashed once I got close to it (about 4 blocks away).

Here is the crashlog: https://pastebin.com/ETEQnj9k

**Comment by copygirl** [comment] 2018-09-27 07:08
Likely a duplicate of #92.

**Closed by copygirl** 2018-09-27 07:08 UTC
Labels: duplicate

**Comment by copygirl** [comment] 2018-09-27 07:12
Mhh. Might have closed too soon. I thought the other issue also had a fix on our end. Let me know if that clears up the cause of the crash, though.

Sorry for being unable to fix the issue for you. Really can't do much when something essentially corrupts the backpack's data.
