### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by Sunconure11** [copygirl/WearableBackpacks#134] opened 2020-05-31 16:51 UTC
https://pastebin.com/UCLqE3Pz

**Comment by copygirl** [comment] 2020-05-31 21:58
Likely a duplicate of #100. Was the backpack moved with Carry On?

**Comment by Sunconure11** [comment] 2020-06-01 01:33
Yes. I had since blacklisted this mod from Carry On.

**Comment by copygirl** [comment] 2020-06-01 05:24
I will close this as a duplicate then. Thank you for reporting it, nonetheless!

**Closed as completed by copygirl** 2020-06-01 05:24 UTC
Labels: duplicate
