### ISSUE TITLE
[Suggestion] Baubles Support

### ISSUE THREAD

**Issue by slave2midna** [copygirl/WearableBackpacks#137] opened 2020-08-12 19:28 UTC
Wanted to say it's a great mod, dig it entirely - would like to throw the suggestion of 'baubles' support. Or at least the option for it.

**Comment by copygirl** [comment] 2020-08-12 19:58
Duplicate of #52. Baubles support possibility is questionable as I don't believe there's a way to prevent items from being unequipped, which would cause all items the player was carrying to be spilled on the ground. Well, in addition to the mod being more or less abandoned.

**Closed as completed by copygirl** 2020-08-12 19:58 UTC
Labels: duplicate

**Comment by slave2midna** [comment] 2020-08-13 12:50
Completely understandable, I should've pointed out [Curious](https://www.curseforge.com/minecraft/mc-mods/curios) is essentially new baubles - and that [Backpacked](https://mrcrayfish.com/mods?id=backpacked) does offer support. -- I apologize if I implied it had to maintain full functionality, what I meant in my suggestion was maybe an optional configuration with the warning of displaced items would suffice (though I actually didn't even think about displaced items, that makes sense entirely). 

I honestly just like the look and feel of this backup as a model compared to all the others. I also love it's support for Mo'Bends - so I figured I'd throw in a suggestion. I should've looked back far enough to be sure it wasn't an open issue. Thank you for the time though! Keep up the good work with it!!

**Comment by copygirl** [comment] 2020-08-13 16:49
I appreciate the suggestion and wouldn't want anyone feeling bad for being turned down, I just wish I could still continue this work in one way or another. Certainly there's a lot of stuff that I would still like to add or make compatible.
