### ISSUE TITLE
Unable to equip backpack

### ISSUE THREAD

**Issue by Keetarin** [copygirl/WearableBackpacks#63] opened 2017-12-07 00:03 UTC
When I set backpack as armor to false it says I've equipped a backpack after deleting the backpack... Also, when I try to clear my inventory after emptying it, the pseudobackpack does not get removed.
Can you make it so that sneak breaking just drops the backpack with inventory intact for when Backpack as armor is disabled.
Edit: When I Say delete I refer to it removing the pack after shift clicking.

**Comment by copygirl** [comment] 2017-12-07 17:28
Sorry, I'm not sure I understand.

- I assume you're using the latest version, 3.1.0?
- Maybe this is just a rare desync issue. Does the problem persist after rejoining the world / server?
- Do you play single or multiplayer? Does the config for `equipAsChestArmor` match with the server?  
  (The configuration should be synchronized on joining, but maybe I messed up and need to fix it.)
- Can you create a new world and try to reproduce the issue, and tell me every step you took?
- Does the issue still occur if you temporarily disable / remove every other mod? (In a **new** world.)

**Comment by Keetarin** [comment] 2017-12-08 18:38
Latest version of Wearable Backpacks for 1.12.2, Single Player, and it does fix itself after relogging (without giving back the pack). 
Basically, I set equipAsChestArmor to false, then after shift mining it it disappears, If I try to pick it up otherwise the inventory drops, which defeats the purpose of installing wearable backpacks.
If I try to put a new backpack in an empty chest slot or shift mine it after reenabling equipAsChestArmor (after the previously mentioned disappearance) it says it is occupied by a backpack already, but armor is able to be equipped/unequipped just fine.
Even with only Wearable Backpacks in a pack on its own it does it.
Extra Note: I usually use Baubles and Thut Wearables alongside it so that I can have it in a baubles slot, but for testing purposes I didn't. Though honestly it would be nice to natively have Baubles compatibility.

**Comment by copygirl** [comment] 2017-12-09 04:56
Wait, I'm confused now. Aren't you just explaining how Wearable Backpacks are **supposed** to work? If you press F5, you should be able to see your backpack being equipped. If `equipAsChestArmor` is off, the backpack will be equipped to a "hidden slot" that you can't see in your inventory screen. You can unequip the backpack by sneaking and right clicking the top of a solid block with an empty hand.

> If I try to put a new backpack in an empty chest armor slot or shift mine it after reenabling equipAsChestArmor [...]

Regardless of whether you change the setting, while having a backpack equipped, the mod should correctly recognize that you're still wearing one. That's why it's telling you about being unable to equip a second backpack.

> I usually use Baubles and Thut Wearables alongside it so that I can have it in a baubles slot, but for testing purposes I didn't. Though honestly it would be nice to natively have Baubles support.

I've been considering adding support for other mod slots but it's non-trivial, considering backpacks need to be locked into those slots, and low-priority, since I already have the `equipAsChestArmor` option. (That's what issue #52 is for.) I currently have my eye on another game ^^

As for the way the backpacks are equipped and unequipped: In case you're unhappy with the design, unfortunately that is intentional. But there's plenty of other mods that do the usual in-inventory style backpacks, such as [Iron Backpacks](https://github.com/gr8pefish/IronBackpacks).

**Comment by copygirl** [comment] 2018-01-22 00:15
Closing due to missing response.

**Closed by copygirl** 2018-01-22 00:15 UTC
Labels: bug
