### ISSUE TITLE
Inventory Tweaks Compatibility?

### ISSUE THREAD

**Issue by 63502** [copygirl/WearableBackpacks#17] opened 2017-02-28 04:10 UTC
If it is possible on your end, could you add it? The wearable backpack had this integration in the original BetterStorage, and its a really helpful thing to have.

**Comment by copygirl** [comment] 2017-02-28 08:35
Duplicate of #9. Has been implemented and will come with the next version.

**Closed by copygirl** 2017-02-28 08:35 UTC
Labels: duplicate, enhancement
