### ISSUE TITLE
Crash picking up a backpack

### ISSUE THREAD

**Issue by lebanni** [copygirl/WearableBackpacks#96] opened 2018-09-30 11:22 UTC
Version : WearableBackpacks-1.12.2-3.1.3.jar, forge-1.12.2-14.23.4.2765-universal.jar

Client crashed. I coudn't reconnect to the server until I removed the mod.

[crash-2018-09-29_21.50.44-client.txt](https://github.com/copygirl/WearableBackpacks/files/2431487/crash-2018-09-29_21.50.44-client.txt)

**Comment by copygirl** [comment] 2018-09-30 15:09
Duplicate of #93 and #92. Thank you for reporting, though!

**Closed by copygirl** 2018-09-30 15:09 UTC
Labels: duplicate
