### ISSUE TITLE
long load times with embers rekindled (x-mod)

### ISSUE THREAD

**Issue by mailleseraph** [copygirl/WearableBackpacks#108] opened 2019-04-04 14:52 UTC
Hello, when loading up a world with embers: rekindled there is a problem with this mod and embers rekindled that causes significantly long load times in recipe loading. problem exists with just embers rekindled, JEI, and wearable backpacks, but the more mods there are the longer the load problem.

the log shows:

https://pastebin.com/ijfgMemq

versions:
forge 14.23.5.2823
wearable backpacks: 1.12.2- 3.1.3
embers rekindled: 1.13
edit: jei version: 4.15.0.271

**Comment by mailleseraph** [comment] 2019-04-04 14:53
issue opened on embers rekindled https://github.com/DaedalusGame/EmbersRekindled/issues/148

**Comment by copygirl** [comment] 2019-04-04 23:53
Semi-duplicate of #75, fixed in 2fd9a491d36eca18f26fdc138dd4a600fa3a6bd7, but there hasn't been a release that includes this fix. Either way, looking at Embers' issue, it looks like this is something for them to address, considering how many other mods are affected.

**Closed by copygirl** 2019-04-04 23:53 UTC
Labels: bug
